name: Machine Learning CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn pandas numpy

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=http://127.0.0.1:5000" >> $GITHUB_ENV

      - name: Run MLflow Project
        run: |
          mlflow run MLProject -P n_estimators=100 -P max_depth=5 --env-manager=local

      - name: Cache Dataset
        id: cache-dataset
        uses: actions/cache@v3
        with:
          path: namadataset_preprocessing/customer_churn_preprocessing.csv
          key: ${{ runner.os }}-dataset

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-trained-artifacts
          path: mlruns/

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        if: success()
        run: |
          mlflow models build-docker -m "runs:/latest/model" -n "andyputrapratama/customer-churn-model:latest"
          docker push andyputrapratama/customer-churn-model:latest
