name: Machine Learning CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn pandas numpy

      - name: Start MLflow Server
        run: |
          nohup mlflow server --host 127.0.0.1 --port 5000 &
          sleep 5

      - name: Run MLflow Project
        run: |
          mlflow run MLProject -P n_estimators=100 -P max_depth=5

      - name: Cache Dataset
        id: cache-dataset
        uses: actions/cache@v4
        with:
          path: MLProject/namadataset_preprocessing/customer_churn_preprocessing.csv
          key: ${{ runner.os }}-dataset

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-trained-artifacts
          path: mlruns/

      - name: Log in to Docker Hub
        continue-on-error: true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        continue-on-error: true
        run: |
          mlflow models build-docker -m "runs:/latest/model" -n "andyputrapratama/customer-churn-model:latest"
          docker push andyputrapratama/customer-churn-model:latest
